CREATE DATABASE readme
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;
USE readme;
CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(128) NOT NULL UNIQUE,
	login VARCHAR(64) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	avatar VARCHAR(255)
);
CREATE TABLE posts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(255),
	content TEXT,
	quote_author VARCHAR(64) NOT NULL,
	image VARCHAR(255),
	video VARCHAR(255),
	link VARCHAR(255),
	num_of_views INT,
	user_id INT NOT NULL,
	content_type_id VARCHAR(64) NOT NULL
);
CREATE INDEX ttl ON posts(title);
CREATE INDEX cntnt ON posts(content);
CREATE TABLE comments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	comment TEXT NOT NULL,
	user_id INT NOT NULL,
	post_id INT NOT NULL
);
CREATE TABLE likes (
	user_id INT NOT NULL,
	post_id INT NOT NULL
);
CREATE TABLE subscription (
	user_id INT NOT NULL,
	subscription_id INT NOT NULL
);
CREATE TABLE messages (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	message TEXT,
	sender_id INT NOT NULL,
	receiver_id INT NOT NULL
);
CREATE TABLE content_type (
	id INT AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR(64) NOT NULL,
	class_name VARCHAR(64) NOT NULL
);